name: CI/CD - Cart Service

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: willchrist/cart
  K8S_NAMESPACE: default

jobs:
  build-and-push:
    runs-on: [self-hosted, Linux, X64]

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2️⃣ Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3️⃣ Build and push Docker image
    - name: Build & Push Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} ./services/cart-service
        docker push $IMAGE_NAME:${{ github.sha }}
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
