name: CI/CD - Cart Service

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: willchrist/cart
  K8S_NAMESPACE: default

jobs:
  build-deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
    # 1. Checkout code
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2. Set up Docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build Docker image
    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker push $IMAGE_NAME:${{ github.sha }}

    # 4. Set up kubectl
    - name: Set Kubernetes context
      uses: azure/setup-kubectl@v3
      with:
        version: v1.32.7
        config-file: ~/.kube/config

    # 5. Update deployment image
    - name: Deploy to Kubernetes
      run: |
        kubectl -n $K8S_NAMESPACE set image deployment/cart-service-deployment \
          cart-service=$IMAGE_NAME:${{ github.sha }}
        kubectl -n $K8S_NAMESPACE rollout status deployment/cart-service-deployment
