name: Runner Test

on:
  workflow_dispatch:  # run manually from Actions tab

jobs:
  test:
    runs-on: self-hosted   # this will target your runner
    steps:
      - name: Say hello
        run: echo "Hello from self-hosted runner $(hostname)"
      - name: Show current user
        run: whoami
      - name: List files
        run: ls -l
